project:
  type: book
  output-dir: docs

book:
  title: "CASA0023 - Remote Sensing Learning Diary"
  author: "Soki Kimura"
  date: "03/23/2024"
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_portfolio.qmd
    - 03_rs_data.qmd
    - 04_policy.qmd
    - 05_gge.qmd
    - 06_classification.qmd
    - 07_accuracy.qmd
    - 08_sar.qmd
    - 99_references.qmd
  sidebar:
    title: "Soki Kimura's Remote Sensing Learning Diary"
    style: "floating"
    background: "light"
    tools:
      - icon: github
        href: https://github.com/sokimura39/RemoteSensingDiary
      - icon: linkedin
        href: https://www.linkedin.com/in/soki-kimura/

bibliography: learning_diary.bib

format:
  html:
    theme: pulse
  pdf:
    documentclass: scrreprt

editor: visual

