project:
  type: book
  output-dir: docs

book:
  title: "RemoteSensingDiary"
  author: "Soki Kimura"
  date: "01/01/2024"
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_portfolio.qmd
    - 99_references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

